[providers]
providers = ['php']

[phases.setup]
nixPkgs = ['php82', 'php82Extensions.pdo_mysql', 'composer']

[phases.build]
cmds = ['composer install --optimize-autoloader --no-dev']

[phases.install]
cmds = []

[start]
cmd = 'vendor/bin/heroku-php-nginx -C nginx.conf public/'